services:
  - type: web
    name: fwi-prediction
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
